services:
  next-and-type:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/next-and-type"
    #   - "/opt/next-and-type/node_modules"
    # environment:
    #   - NEXT_WEBPACK_USEPOLLING=true
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true